contrib/Dockerfile, contrib/Makefile
This brings it back to 2.2GB:
docker image ls
REPOSITORY   TAG       IMAGE ID       CREATED                  SIZE
key1         latest    7456feccd2fd   Less than a second ago   2.22GB
=> Reduce final Docker image size

hw/application_fpga/fw/mta1_mkdf/start.S
Since SRAM has some data remanence even without power it seems good hygien to clear all RAM when starting the device so as not to leak potentially sensitive data between device apps.
=> FW: Clear all RAM during start

.gitignore, doc/quickstart.md, hw/application_fpga/tools/reset-tk1, hw/boards/mta1-usb-v1/test/hid_test.py, hw/boards/mta1-usb-v1/test/requirements.txt, hw/boards/mta1-usb-v1/test/reset.py
This adds a test script demonstrating how to use the programmer board to issue a hardware reset on a connected mta1-usb-v1 device.
=> Add software reset example for the mta1 programmer

contrib/Dockerfile, contrib/Makefile
- Add a small menu of build targets
- Add podman support, both building the image, creating a container of the image and running shell, and running make inside a podman image.
We should perhaps also add stuff like pushing to our own ghcr?
=> build tools: Add podman support

doc/toolchain_setup.md
* Remove 'Optional' section from README, and update titles of sub-sections.
* Add link to sub-directory with CH552 setup instructions
* Fix line lengths in programmer board section
=> toolchain setup: link to CH552 build instructions

hw/application_fpga/fw/tk1/lib.c
This PR should silence the timing side channel in memeq caused by early return.
=> Make memeq function side channel silent

hw/application_fpga/Makefile
Let's include debug symbols in the ELF binaries so we can use it with GDB easier.
=> Include debug symbols in the ELF

hw/application_fpga/core/uart/rtl/uart_core.v
Fixes error messages like these in Lattice Diamond 3.12 / Verilog 2001:
```
(VERI-1906) net type must be explicitly specified for `rx_data`
when default_nettype is none
```
```
(VERI-1195) concurrent assignment to a non-net `rx_data` is not
permitted
```
Fix tested through;
```
docker run --rm -it -v$PWD:/opt/src:ro ghcr.io/tillitis/tkey-builder:2
bash -c  
"cp -r /opt/src /opt/build && 
cd /opt/build/hw/application_fpga && 
make clean &&
make lint &&
make all"
```
=> Explicity make uart_core.rx_data a wire

hw/application_fpga/rtl/fw_ram.v
Verilog 2001 rule; use wires for assignments, not registers.
Increase verilog source code compatibility with Lattice Diamond 3.12.
Address errors like these:
```
2049990 ERROR - tillitis-key1/hw/application_fpga/rtl/fw_ram.v
(VERI-1195) concurrent assignment to a non-net 'fw_app_cs' is
not permitted
```
Tool drop down menu supports either System Verilog, Verilog 2001, Verilog 95, with Verilog 2001 being default.
(No Verilog 2005 in drop down menu, even if old PDFs does say Verilog 2005 is supported...)
Patch tested as follows:
```
docker run -it -v$PWD:/opt/src ghcr.io/tillitis/tkey-builder:2
bash -c
"cp -r /opt/src /opt/build &&
cd /opt/build/hw/application_fpga &&
make clean &&
make lint &&
make all"
```
=> Verilog 2001 rule; use wires for assignments, not registers.

hw/boards/mta1-usb-v1/ch552_fw/include/debug.c, hw/boards/mta1-usb-v1/ch552_fw/include/debug.h, hw/boards/mta1-usb-v1/ch552_fw/main.c
This is a fix for the issue that CH552 during certain circumstances can drop a bytes from UART -> USB.
Some other changes:
- Implemented simple GPIO usage, for debugging. Left it in for future use but uninitialized. 
- Translated all comments (hence why the PR looks so messy).
- Left comments at locations I see potential issues with, as a reminder for the future.
=> Protecting input/output buffers of CH552

contrib/Dockerfile
First stab at updating to tkey-builder:3.
Joachim says we might need latest and greatest yosys and nextpnr, though, so draft.
=> Update to Ubuntu 23.10 and latest released yosys & nextpnr

hw/application_fpga/Makefile, hw/application_fpga/fw/testfw/main.c, hw/application_fpga/fw/tk1/main.c, hw/application_fpga/fw/tk1/proto.c, hw/application_fpga/fw/tk1/proto.h, hw/application_fpga/fw/tk1_mem.h
Turning on `-W pedantic` shows us that our memory constants can't fit in an enum in ISO C. Not a real problem for GNU99 but makes it hard to run `-W pedantic` to find other problems.
I propose we change the memory constants from an enum into pre-processor defines instead and use simple direct values for the memory addresses instead of computing them.
We also turn on pedantic warnings but allow inline asm as the GNU extension we mostly use and fix missing void parameter declarations that pedantic warned us about.
Please review carefully that have all the addresses defined.
Also note that `tk1_mem.h` is also used in `tkey-libs` and `qemu`.
Closes #159
=> Memory map constants as defines

README.md, doc/framing_protocol/framing_protocol.md, doc/quickstart.md, doc/system_description/software.md, doc/system_description/system_description.md, doc/toolchain_setup.md
Updated readme and docs that has been outdated. 
Kept old documentation for the sake of history, but added a note pointing towards dev.tillitis.
=> Updated readme and docs to point at dev.tillitis.se.

contrib/Dockerfile, contrib/Makefile, hw/application_fpga/Makefile
=> Add Icarus Verilog compiler, simulator used by testbenches

contrib/Dockerfile
To be able to run statical analysis on source, include clang-tidy and splint (see make check) in tkey-builder.
=> tkey-builder: Include clang-tidy & splint

.github/workflows/ci.yaml
closes #96 
Depends on a tkey-builder with pico-sdk 1.5.1, see: #190 
Need to build and push a tkey-builder:4, probably, and update in this branch to use :4.
=> Build tp1 firmware in CI

hw/application_fpga/Makefile, hw/application_fpga/tools/patch_uds_udi.py
Changed filename in order to be a bit less cryptic about what the python script does.
Also adding a more detailed explanation about what it intends to do.
=> Adding explanation and changing name of personalize.py

hw/application_fpga/core/tk1/README.md, hw/application_fpga/core/uds/README.md, hw/application_fpga/tools/patch_uds_udi.py
An attempt at updating the documentation in the tk1 and uds cores about the new storage of the UDI and UDS.
Updates the comment in the patch script to describe what it does and how to run instead of focusing on the storage solution.
If I misunderstood something there's no need to comment and ask me to update, just commit a correction. If there are things up for discussion, please comment.
=> Update UDS/UDI storage implementation documentation

.github/workflows/ci.yaml
- This makes it easier to see if CI fails on hashes (which might be expected during development) or something else.
=> CI: move check-hash to separate job.

.github/workflows/ci.yaml
Divide CI in separate jobs, categorized a bit better.
Cache: Fixed a bug and also fixed a potential issue with the cache strategy, where it could lead to the wrong bitstream being fetched if the original key was not found. This is solved now, now each and every run will create a unique key, and if the cache for some reason fails, the check-hash will fail instead of fetching a different bitstream.
=> Divide CI in separate jobs

hw/application_fpga/core/touch_sense/README.md
Clarify how the touch_sense core works, and fix the language.
=> Clarify the functional description of the touch_sense core

hw/application_fpga/core/tk1/tb/udi_rom_sim.v, hw/application_fpga/core/tk1/toolruns/Makefile
This PR adds a simulation model of the udi_rom. This allows us to build the testbench and simulated the tk1 core. This PR does not change the actual FPGA design.
=> FPGA: Add sim model of udi_rom

hw/application_fpga/core/tk1/tb/sb_rgba_drv.v, hw/application_fpga/core/tk1/toolruns/Makefile
This PR fixes linting of the tk1 core. It adds the udi_rom and sb_rbga_led simulation models used to replace the Lattice core instantiations done in the RTL. We also add ignore-pragmas to disable lint warnings on things not supported in the sim model of the rgba core.
=> Fix tk1 lint

hw/application_fpga/Makefile, hw/application_fpga/core/picorv32/rtl/picorv32.v, hw/application_fpga/core/picorv32/toolruns/Makefile
A set of fixes to allow separate linting of the PicoRV32 and fixes to the PicoRV32 RTL that does not affect the implementation. The set of fixes also includes no flags to the linter to ignore warnings in the cell library.
=> Fpga lint fixes

hw/application_fpga/core/tk1/rtl/tk1.v
Remove the preceeding zero in the constant expression
that cause the simulator to warn about incorrect
bit size.
When building the tk1 simulation target, the simulator complains that the constant value given doesn't match the specified size of the constant. The problem is that 'h01' is not seen by the simulator as being two bits. One could possibly have used binary format instead of hex format. But 'h1' removes the warning.
Fixes # (issues)
No previous issue exists.
=> fpga: Fix nits in constant value specification

hw/application_fpga/core/tk1/rtl/tk1_spi_master.v, hw/application_fpga/core/tk1/tb/tb_tk1.v, hw/application_fpga/core/tk1/tb/tb_tk1_spi_master.v
Update name of Winbond model
Remove DUT variables from state display that was
removed as part of performance fix
This PR fix regressions in testbench build and the testbench itself:
1. Update the name of the Winbond SPI memory model that one now gets when downloading the model from Windbond website. Both in Makefile and the testbench
2. Remove the clock counter control signal and register from the DUT state display in the testbench. These were removed as part of RTL update to maximize the SPI speed. Basically we don't run below what we can get with the given clock frequency.
Fixes # (issues)
No issue assigned before. Found during other bug hunt.
=> fpga: Cleanup testbench and testbench build

hw/application_fpga/Makefile, hw/application_fpga/application_fpga.bin.sha256, hw/application_fpga/core/uart/rtl/uart.v, hw/application_fpga/rtl/clk_reset_gen.v
FPGA clock increased to 21 MHz
UART bitrate increased to 500 kbps
=> FPGA: Increase clock frequency to 21 MHz

.gitignore, hw/application_fpga/Makefile
* Break long lines and use tab to indent
* Remove use of "tee" since it messes up the return status
* Remove the generated application_fpga_par.json if nextpnr-ice40 fails on timing.
* Change log file ending from .log to .txt
* Fix some spacing
=> Fix makefile lines and tee exit status problem

hw/application_fpga/fw/tk1/proto.c, hw/application_fpga/fw/tk1/proto.h
The frame_header has the wrong type in the struct. It is not used as the enum, it is used for the actual length.
This does note seem to change the actual binary output, but I would still argue it should be the type `size_t`. 
As it is in tkey-libs.
=> fw: Fix erroneous type in frame header

contrib/Makefile, hw/application_fpga/Makefile, hw/application_fpga/core/tk1/README.md, hw/application_fpga/core/tk1/tb/tb_tk1.v
- Add clean target for the testbench generated files
- Add it so it always cleans in contrib/Makfile
- Fix broken tk1 testbench after name change
Testbenches are not running in CI yet, so run it manually using `make tb` in `hw/application_fpga` or `make run-tb` in `contrib`. 
FYI: the testbench for uds_rom is already broken, see: https://github.com/tillitis/tillitis-key1/issues/260
=> Fix testbench for tk1

contrib/Makefile, hw/application_fpga/Makefile, hw/application_fpga/application_fpga.bin.sha256, hw/application_fpga/core/tk1/rtl/tk1.v, hw/application_fpga/core/tk1/toolruns/Makefile, hw/application_fpga/rtl/application_fpga.v
Suggestion: Always include SPI master in build.
Pro:
- It's easy to miss to include the SPI master. 
- There are a lot of ugly ifdefs in the design.
Con:
- We may want to keep it possible to build without SPI and flash access for future releases of Bellatrix-compatible versions. One suggestion, however, is to support that through software with something in the flash saying that flash isn't available and then turning off the future flash code in the firmware.
=> Include SPI master in default build

contrib/Dockerfile
- Change docker image to ubuntu 24.04
- Add new versions of:
* clang (18.1.3, part of ubuntu 24.04)
* icestorm (commit 738af822905fdcf0466e9dd784b9ae4b0b34987f)
* yosys (0.45)
* nextpnr (0.7) + extra patches for RNG seed handling and early exit
* iverilog (v12)
* verilator (v5.028)
* verible (v0.0-3795)
* cocotb (v1.9.1)
- Remove:
* gcc-arm-none-eabi
* libnewlib-arm-none-eabi
* libstdc++-arm-none-eabi-newlib
* splint
* pico-sdk
* golang
Add lint flag needed for new Verilator version.
=> Update toolchain with new versions of FPGA tools and remove fw/apps/programmer toolschains

hw/application_fpga/Makefile, hw/application_fpga/application_fpga.bin.sha256
* -abc2, run two passes of 'abc' for slightly improved logic density
* -device u, optimize timing for up5k device
* -dff, run 'abc'/'abc9' with -dff (D flip flop) option
=> Add yosys flags to optimize synthesis

contrib/Makefile
Fixes an issue with running `make -C contrib flash`  (Command found in the [dev guide](https://dev.tillitis.se/unlocked/spiflash/#2-program-spi-flash)). The command exits with the following error: 
`Error: workdir "/build/hw/application_fpga" does not exist on container`
Fixed by setting the working directory to /build.
Previously the working directory was set to `/build/hw/application_fpga`. But that path does not exist since `hw/application_fpga` is already mounted to `/build`. Thus resulting in an error.
=> Fix flash target in contrib/Makefile

hw/application_fpga/core/fw_ram/README.md
fix typo of system mode in readme
=> Doc: fix typo of system mode in readme

contrib/Dockerfile, hw/application_fpga/tools/run_pnr.sh
* Add flag so we can keep nextpnr standard behavior and if this flag is used we can get a fast exit if timing fails on placement.
* Update run_pnr.sh script to use this flag
=> Add nextpnr flag '--exit-on-failed-target-frequency'

hw/application_fpga/application_fpga.bin.sha256, hw/application_fpga/core/timer/README.md, hw/application_fpga/core/timer/rtl/timer_core.v, hw/application_fpga/core/timer/tb/tb_timer.v, hw/application_fpga/core/timer/tb/tb_timer_core.v
Fix a bug in the timer core, where it misses clock cycles. It is fixed by removing a redundant timer state.
The clock cycle misses every time the prescaler counter reaches 1. This means if one uses a large prescaler, like 18E6, it is barely noticeable, but if one have a low prescaler and a high timer value it becomes significant.
Hardware timers are, according to me, usually a function of:
`f_time = f_freq / (prescaler * period)`
Our `period` us our `timer` register. 
So the prescaler is used to divide the system clock to yield a timer with a wanted time for each tick.
To exemplify the issue:
If I use above and want the ticks in microseconds and I want the timer to expire after 1 millisecond.
I use 18 Mhz frequency as an example.
1 ms = 18 * 10^6 / ( 18 * 1000 ).
This means it needs 18 …
=> Fix timer + timer testbenches

.gitignore, hw/application_fpga/Makefile, hw/application_fpga/application_fpga.bin.sha256, hw/application_fpga/core/tk1/rtl/tk1.v, hw/application_fpga/fw/tk1/main.c, hw/application_fpga/tb/application_fpga_sim.v, hw/application_fpga/tb/application_fpga_verilator.cc, hw/application_fpga/tb/reset_gen_sim.v, hw/application_fpga/tb/tb_application_fpga_sim.v, hw/application_fpga/tb/trng_sim.v, hw/application_fpga/tools/app_bin_to_spram_hex.py
Add files and functionality to simulate an app on the top level of appliaction FPGA.
=> Add files and functionality to simulate an app on the top level.

hw/application_fpga/core/tk1/tb/tb_tk1.v, hw/application_fpga/core/tk1/tb/tb_tk1_spi_master.v, hw/application_fpga/core/touch_sense/tb/tb_touch_sense.v, hw/application_fpga/core/trng/tb/tb_trng.v, hw/application_fpga/core/uart/tb/tb_uart.v
Make testbenches selftesting by:
1. Exit with the right error code
2. Comparing the output with the expected result
Fixes # (issues)
=> Make testbenches selftesting

hw/application_fpga/Makefile
synth.json shouldn't depend on uds.hex and udi.hex because that triggers a complete rebuild of the bitstream if the UDI or UDS are changed.
Instead, we want only the `application_fpga.asc` target to depend on them, so it can patch in the changed UDS and UDI with `tools/patch_uds_udi.py` in an existing `application_fpga_par.json`.
=> Build: Don't depend on uds.hex and udi.hex

hw/usb_interface/ch552_fw/include/debug.c, hw/usb_interface/ch552_fw/include/debug.h, hw/usb_interface/ch552_fw/main.c
- Move "EndpointXUploadBusy = 1" to before USB transfer is started to fix race with USB transfer complete interrupt.
- Move copying of TKEYCTRL data from UartRxBuf to TkeyCtrlRxBuf to align with previous code.
- Remove obsolete UartRxBufOverflow variable.
- Add missing Endpoint4 handling for USB bus reset.
- Fix more robust uart_byte_count() calculation.
- Fix baudrate fast mode calculation to get rid of compiler warning.
- Fix assignment of bUD_PD_DIS to UDEV_CTRL.
- Cleanup comments.
Fixes #319 
=> ch552: Fix race condition + misc. stuff

contrib/Makefile, hw/application_fpga/Makefile
Simplifies the process of getting a TKey into a functional state out of the box.
Instead of building and flashing bitstream, partition table and testloadapp.bin separately you can now run `make -C contrib flash` or `make -C hw/application prog_flash`.
Also removes the use of sudo in the tillitis-iceprog calls. It should not be needed if proper permissions has been setup for the tp-1.
=> Simplify flashing bitstream, partition table and testloadapp.bin

hw/application_fpga/fw/tk1/main.c
Building `qemu_firmware.bin`:
```
cd contrib
make run
cd hw/application_fpga
make clean_fw
make qemu_firmware.elf
```
Produce the following warnings:
```
/build/hw/application_fpga/fw/tk1/main.c:452:16: warning: passing 'volatile uint8_t[32]' (aka 'volatile unsigned char[32]') to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
452 |         debug_hexdump(resetinfo->app_digest, RESET_DIGEST_SIZE);
|                       ^~~~~~~~~~~~~~~~~~~~~
tkey-libs/include/tkey/debug.h:17:50: note: expanded from macro 'debug_hexdump'
17 | #define debug_hexdump(buf, len) hexdump(IO_QEMU, buf, len)
|                                                  ^~~
tkey-libs/include/tkey/io.h:39:37: note: passing argument to parameter 'buf' here
39 | void hexdump(enum …
```
=> Fix qemu_firmware build warnings

contrib/Dockerfile
- Add Go 1.23.
- Set up PATH for container to include the Go binaries.
I have rebuilt the image and built the bitstream. It's still reproducible. No changes to the firmware binary even though we haven't locked down the version of clang, llvm, ...
=> toolchain: Add Go package

hw/application_fpga/apps/Makefile, hw/application_fpga/apps/loopbackapp/main.c
This app takes data coming in on any of the normal USB endpoints like CDC and FIDO (or CCID) and outputs the data on the DEBUG endpoint.
Using the scripts (tkey_to_udp_linux.py, tkey_to_udp_win.py) in QEMU (tk1 branch) under tools/tk1, the data from the DEBUG endpoint can be read and sent over the network to the script udp_to_qemu_linux.py that feeds it to QEMU.
=> Add loopbackapp for app debugging using physical TKey with QEMU
